POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Video teste",
  "description": "Esse é o video 02",
  "duration": 180
}

### 

GET http://localhost:3333/videos
// GET http://localhost:3333/videos?search=node

### 

PUT http://localhost:3333/videos/1ce698d6-488e-40d4-9135-4d5e72871b3a
Content-Type: application/json

{
  "title": "Video node",
  "description": "Esse é o video 01",
  "duration": 180
}

### 

DELETE  http://localhost:3333/videos/928e2303-2a1d-4fc9-a599-b60a0e5b4f7b